site_name: Yoga
site_url: https://yoga.example
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  # logo: assets/logo.png
  # favicon: assets/favicon.ico
  features:
    - navigation.footer
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: deep orange
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: indigo
      accent: teal

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/king-luvaha
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ezra-yeswa/

copyright:
  © 2025 <a href="https://github.com/king-luvaha" target="_blank" rel="noopener">Ezra Luvaha</a>